# Generated by Django 4.2 on 2023-05-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Ціна (грн)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_for_all',
            field=models.IntegerField(verbose_name='Ціна за всі одиниці продукту (грн)'),
        ),
        migrations.AlterField(
            model_name='surovuna',
            name='delivery_price',
            field=models.IntegerField(verbose_name='Ціна доставки (грн)'),
        ),
        migrations.AlterField(
            model_name='surovuna',
            name='quantity_on_plant',
            field=models.IntegerField(verbose_name='Кількість сировини на заводі (тонн)'),
        ),
        migrations.AlterField(
            model_name='surovuna',
            name='vurobnucha_price_general_kg',
            field=models.IntegerField(verbose_name='Загальна ціна за сировину (грн)'),
        ),
        migrations.AlterField(
            model_name='surovuna',
            name='vurobnucha_price_kg',
            field=models.IntegerField(verbose_name='Ціна за кілограм сировини (грн)'),
        ),
    ]
