# Generated by Django 4.2 on 2023-05-10 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0002_remove_customer_password_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Доступний продукт', 'verbose_name_plural': 'Доступних продуктів'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Замовник'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='surovuna_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.surovuna', verbose_name='Ідентифікатор сировини'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
