# Generated by Django 4.2 on 2023-05-10 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_product_options_remove_order_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'замовлення', 'verbose_name_plural': 'замовлень'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'доступний продукт', 'verbose_name_plural': 'доступних продуктів'},
        ),
        migrations.AlterModelOptions(
            name='surovuna',
            options={'verbose_name': 'запис', 'verbose_name_plural': 'записів'},
        ),
    ]
